name: Daily Package Upgrades

on:
  push:
    branches:
      - main
      - develop
  schedule:
    - cron: "0 0-23/4 * * *"

jobs:
  upgrade-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Upgrade packages
        run: yarn upgrade
      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.email ${{ github.actor }}@users.noreply.github.com
            git config user.name ${{ github.actor }}
            git add .
            git commit -m "Auto-upgraded packages $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
            git push https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
